namespace Library_Management_System.Models.Enums
{
    public enum Genre
    {
        SF,
        Fantasy,
        Dystopian,
        ActionAdventure,
        Mystery,
        Horror,
        Thriller,
        Romance,
        Realism,
        GraphicNovel,
        ShortStory,
        YoungAdult,
        Children,
        Autobiography,
        Biography, 
        FoodDrink,
        Art,
        History,
        Travel,
        SelfHelp,
        Humour,
        HowTo,
        ReligionSpirituality,
        SocialSciences,
        Parenting,
        ScienceTechnology
    }
}
